// ---
// THIS FILE IS AUTO-GENERATED BY WEA (Web Elements Analyzer).
// DO NOT EDIT MANUALLY — your changes will be overwritten.
// ---
interface CustomElementsLocal {
	/**
	 * ```jsx
	 * class LitRenderer extends LitElement (<lit-renderer>)
	 * ```
	 * ---
	 * @property `template` — {`HTMLTemplateResult | null`}
	 */
	'lit-renderer': {
		elementClass: HTMLElementTagNameMap['lit-renderer'];
		properties: {
			template?: HTMLElementTagNameMap['lit-renderer']['template'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaNodeElement extends SignalWatcher(LitElement) (<nf-wa-node>)
	 * ```
	 * ---
	 * @attribute `i18n` — {`{ settings?: string; delete?: string; ok?: string; }`}
	 * @property `isNodeInfosEditModeActive` — {`boolean`}
	 * @property `isDeleting` — {`boolean`}
	 * @property `node` — {`GenericNode`}
	 * @property `i18n` — {`{ settings?: string; delete?: string; ok?: string; }`}
	 */
	'nf-wa-node': {
		elementClass: HTMLElementTagNameMap['nf-wa-node'];
		properties: {
			isNodeInfosEditModeActive?: HTMLElementTagNameMap['nf-wa-node']['isNodeInfosEditModeActive'];
			isDeleting?: HTMLElementTagNameMap['nf-wa-node']['isDeleting'];
			node?: HTMLElementTagNameMap['nf-wa-node']['node'];
			/**
			 * @attribute `i18n`
			 */
			i18n?: HTMLElementTagNameMap['nf-wa-node']['i18n'];
		};
		attributes: {
			/**
			 * @property `i18n`
			 */
			i18n?: unknown;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaPortElement extends SignalWatcher(LitElement) (<nf-wa-port>)
	 * ```
	 * ---
	 * @property `port` — {`GenericPort`}
	 */
	'nf-wa-port': {
		elementClass: HTMLElementTagNameMap['nf-wa-port'];
		properties: {
			port?: HTMLElementTagNameMap['nf-wa-port']['port'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaBroadcastChannelElement extends SignalWatcher(LitElement) (<wf-broadcast-channel>)
	 * ```
	 * ---
	 * @property `messageInput` — {`GenericPort`}
	 * @property `messageOutput` — {`GenericPort`}
	 * @property `defaultValue` — {`string`}
	 * @property `channel` — {`import("@lit-labs/signals").Signal.State<string>`}
	 */
	'wf-broadcast-channel': {
		elementClass: HTMLElementTagNameMap['wf-broadcast-channel'];
		properties: {
			messageInput?: HTMLElementTagNameMap['wf-broadcast-channel']['messageInput'];
			messageOutput?: HTMLElementTagNameMap['wf-broadcast-channel']['messageOutput'];
			defaultValue?: HTMLElementTagNameMap['wf-broadcast-channel']['defaultValue'];
			channel?: HTMLElementTagNameMap['wf-broadcast-channel']['channel'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCanvasColorElement extends SignalWatcher(LitElement) (<nf-canvas-color>)
	 * ```
	 * ---
	 * @property `canvasOut` — {`Port<HTMLCanvasElement, any> | null`}
	 * @property `textIn` — {`Port<string, any> | null`}
	 * @property `color` — {`string`}
	 */
	'nf-canvas-color': {
		elementClass: HTMLElementTagNameMap['nf-canvas-color'];
		properties: {
			canvasOut?: HTMLElementTagNameMap['nf-canvas-color']['canvasOut'];
			textIn?: HTMLElementTagNameMap['nf-canvas-color']['textIn'];
			color?: HTMLElementTagNameMap['nf-canvas-color']['color'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCanvasComparerElement extends SignalWatcher(LitElement) (<nf-wa-canvas-comparer>)
	 * ```
	 * ---
	 * @property `canvasBeforeIn` — {`Port<HTMLCanvasElement, any>`}
	 * @property `canvasAfterIn` — {`Port<HTMLCanvasElement, any>`}
	 * @property `blurFactor` — {`number`}
	 */
	'nf-wa-canvas-comparer': {
		elementClass: HTMLElementTagNameMap['nf-wa-canvas-comparer'];
		properties: {
			canvasBeforeIn?: HTMLElementTagNameMap['nf-wa-canvas-comparer']['canvasBeforeIn'];
			canvasAfterIn?: HTMLElementTagNameMap['nf-wa-canvas-comparer']['canvasAfterIn'];
			blurFactor?: HTMLElementTagNameMap['nf-wa-canvas-comparer']['blurFactor'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCanvasFiltersElement extends SignalWatcher(LitElement) (<nf-wa-canvas-filters>)
	 * ```
	 * ---
	 * @property `canvasIn` — {`Port<HTMLCanvasElement, any>`}
	 * @property `canvasOut` — {`Port<HTMLCanvasElement, any>`}
	 * @property `blurIn` — {`Port<number, any>`}
	 * @property `brightnessIn` — {`Port<number, any>`}
	 */
	'nf-wa-canvas-filters': {
		elementClass: HTMLElementTagNameMap['nf-wa-canvas-filters'];
		properties: {
			canvasIn?: HTMLElementTagNameMap['nf-wa-canvas-filters']['canvasIn'];
			canvasOut?: HTMLElementTagNameMap['nf-wa-canvas-filters']['canvasOut'];
			blurIn?: HTMLElementTagNameMap['nf-wa-canvas-filters']['blurIn'];
			brightnessIn?: HTMLElementTagNameMap['nf-wa-canvas-filters']['brightnessIn'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCanvasMixerElement extends SignalWatcher(LitElement) (<wf-canvas-mixer>)
	 * ```
	 * ---
	 * @property `canvasAIn` — {`Port<HTMLCanvasElement, any> | null`}
	 * @property `canvasBIn` — {`Port<HTMLCanvasElement, any> | null`}
	 * @property `canvasOut` — {`Port<HTMLCanvasElement, any> | null`}
	 */
	'wf-canvas-mixer': {
		elementClass: HTMLElementTagNameMap['wf-canvas-mixer'];
		properties: {
			canvasAIn?: HTMLElementTagNameMap['wf-canvas-mixer']['canvasAIn'];
			canvasBIn?: HTMLElementTagNameMap['wf-canvas-mixer']['canvasBIn'];
			canvasOut?: HTMLElementTagNameMap['wf-canvas-mixer']['canvasOut'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCanvasTextElement extends SignalWatcher(LitElement) (<nf-canvas-text>)
	 * ```
	 * ---
	 * @property `canvasOut` — {`Port<HTMLCanvasElement, any> | null`}
	 * @property `textIn` — {`Port<string, any> | null`}
	 */
	'nf-canvas-text': {
		elementClass: HTMLElementTagNameMap['nf-canvas-text'];
		properties: {
			canvasOut?: HTMLElementTagNameMap['nf-canvas-text']['canvasOut'];
			textIn?: HTMLElementTagNameMap['nf-canvas-text']['textIn'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaNoteElement extends SignalWatcher(LitElement) (<nf-wa-note>)
	 * ```
	 * ---
	 * @property `textContent` — {`string`}
	 */
	'nf-wa-note': {
		elementClass: HTMLElementTagNameMap['nf-wa-note'];
		properties: {
			textContent?: HTMLElementTagNameMap['nf-wa-note']['textContent'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaCenterElement extends SignalWatcher(LitElement) (<nf-wa-center>)
	 * ```
	 * ---
	 * @property `slot` — {`"background-interactive"`}
	 * @property `flow` — {`Flow<import("@node-flow-elements/core/types").NodeRegistry>`}
	 */
	'nf-wa-center': {
		elementClass: HTMLElementTagNameMap['nf-wa-center'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-wa-center']['slot'];
			flow?: HTMLElementTagNameMap['nf-wa-center']['flow'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaInventoryElement extends SignalWatcher(LitElement) (<nf-wa-inventory>)
	 * ```
	 * ---
	 * @attribute `i18n` — {`{ cancel?: string; confirm?: string; clearAll?: string; autoLayout?: string; clearCanvas?: string; confirmMessage?: string; pressEnterHint?: string; nodes?: string; }`}
	 * @property `slot` — {`"foreground"`}
	 * @property `flow` — {`Flow<import("@node-flow-elements/core/types").NodeRegistry>`}
	 * @property `i18n` — {`{ cancel?: string; confirm?: string; clearAll?: string; autoLayout?: string; clearCanvas?: string; confirmMessage?: string; pressEnterHint?: string; nodes?: string; }`}
	 * @property `MenuPanel` — {`(tree: MenuItem[]) => HTMLTemplateResult[]`}
	 */
	'nf-wa-inventory': {
		elementClass: HTMLElementTagNameMap['nf-wa-inventory'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-wa-inventory']['slot'];
			flow?: HTMLElementTagNameMap['nf-wa-inventory']['flow'];
			/**
			 * @attribute `i18n`
			 */
			i18n?: HTMLElementTagNameMap['nf-wa-inventory']['i18n'];
			MenuPanel?: HTMLElementTagNameMap['nf-wa-inventory']['MenuPanel'];
		};
		attributes: {
			/**
			 * @property `i18n`
			 */
			i18n?: unknown;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaMinimapElement extends SignalWatcher(LitElement) (<nf-wa-minimap>)
	 * ```
	 * ---
	 * @attribute `width` — {`number`}
	 * @attribute `height` — {`number`}
	 * @property `slot` — {`"foreground"`}
	 * @property `flow` — {`Flow<import("@node-flow-elements/core/types").NodeRegistry>`}
	 * @property `scale` — {`number`}
	 * @property `width` — {`number`}
	 * @property `height` — {`number`}
	 * @property `updateCanvas` — {`() => void`}
	 */
	'nf-wa-minimap': {
		elementClass: HTMLElementTagNameMap['nf-wa-minimap'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-wa-minimap']['slot'];
			flow?: HTMLElementTagNameMap['nf-wa-minimap']['flow'];
			scale?: HTMLElementTagNameMap['nf-wa-minimap']['scale'];
			/**
			 * @attribute `width`
			 */
			width?: HTMLElementTagNameMap['nf-wa-minimap']['width'];
			/**
			 * @attribute `height`
			 */
			height?: HTMLElementTagNameMap['nf-wa-minimap']['height'];
			updateCanvas?: HTMLElementTagNameMap['nf-wa-minimap']['updateCanvas'];
		};
		attributes: {
			/**
			 * @property `width`
			 */
			width?: number;
			/**
			 * @property `height`
			 */
			height?: number;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfWaNavigationElement extends SignalWatcher(LitElement) (<nf-wa-navigation>)
	 * ```
	 * ---
	 * @property `slot` — {`"foreground"`}
	 * @property `flow` — {`Flow<import("@node-flow-elements/core/types").NodeRegistry>`}
	 */
	'nf-wa-navigation': {
		elementClass: HTMLElementTagNameMap['nf-wa-navigation'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-wa-navigation']['slot'];
			flow?: HTMLElementTagNameMap['nf-wa-navigation']['flow'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
}
interface GlobalCss {
	properties: {};
}
declare global {
	interface HTMLElementTagNameMap {
		'lit-renderer': import('./../lit-renderer.el.js').LitRenderer;
		'nf-wa-node': import('./../node.el.js').NfWaNodeElement;
		'nf-wa-port': import('./../port.el.js').NfWaPortElement;
		'wf-broadcast-channel': import('./../demo-nodes/broadcast-channel.el.js').NfWaBroadcastChannelElement;
		'nf-canvas-color': import('./../demo-nodes/canvas-color.el.js').NfWaCanvasColorElement;
		'nf-wa-canvas-comparer': import('./../demo-nodes/canvas-comparer.el.js').NfWaCanvasComparerElement;
		'nf-wa-canvas-filters': import('./../demo-nodes/canvas-filters.el.js').NfWaCanvasFiltersElement;
		'wf-canvas-mixer': import('./../demo-nodes/canvas-mixer.el.js').NfWaCanvasMixerElement;
		'nf-canvas-text': import('./../demo-nodes/canvas-text.el.js').NfWaCanvasTextElement;
		'nf-wa-note': import('./../demo-nodes/note.el.js').NfWaNoteElement;
		'nf-wa-center': import('./../extra/center.el.js').NfWaCenterElement;
		'nf-wa-inventory': import('./../extra/inventory.el.js').NfWaInventoryElement;
		'nf-wa-minimap': import('./../extra/minimap.el.js').NfWaMinimapElement;
		'nf-wa-navigation': import('./../extra/navigation.el.js').NfWaNavigationElement;
	}
	interface GlobalEventHandlersEventMap {}
}
import type { CustomElementsExternals } from './web-elements.exts';
interface CustomElements extends CustomElementsLocal, CustomElementsExternals {}
export type {
	CustomElements,
	CustomElementsLocal,
	GlobalCss,
	CustomElementsExternals,
};

declare module 'jsx-forge/jsx-runtime' {
	namespace JSX {
		interface IntrinsicElements
			extends JSX.MappedCustomElements<CustomElements, JSX.BaseHTMLElement> {}
	}
}
