// ---
// THIS FILE IS AUTO-GENERATED BY WEA (Web Elements Analyzer).
// DO NOT EDIT MANUALLY — your changes will be overwritten.
// ---
interface CustomElementsLocal {
	/**
	 * ```jsx
	 * class NfBackgroundElement extends SignalWatcher(LitElement) (<nf-background>)
	 * ```
	 * ---
	 * @attribute `pattern` — {`"lines" | "dots"`} — Grid pattern style.
	 * @attribute `no-rescale` — {`boolean`} — Disable adaptive coarsening of the grid when zoomed out.
	 * @property `slot` — {`"background"`}
	 * @property `flow` — {`GenericFlow`}
	 * @property `pattern` — {`"lines" | "dots"`} — Grid pattern style.
	 * @property `noRescale` — {`boolean`} — Disable adaptive coarsening of the grid when zoomed out.
	 * @cssProperty `--nf-background-color`
	 * @cssProperty `--nf-background-grid-lines-color`
	 * @cssProperty `--nf-background-grid-line-width`
	 * @cssProperty `--nf-background-grid-line-spacing`
	 */
	'nf-background': {
		elementClass: HTMLElementTagNameMap['nf-background'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-background']['slot'];
			flow?: HTMLElementTagNameMap['nf-background']['flow'];
			/**
			 * @attribute `pattern`
			 * @reflects
			 */
			pattern?: HTMLElementTagNameMap['nf-background']['pattern'];
			/**
			 * @attribute `noRescale`
			 * @reflects
			 */
			noRescale?: HTMLElementTagNameMap['nf-background']['noRescale'];
		};
		attributes: {
			/**
			 * @property `pattern`
			 */
			pattern?: 'lines' | 'dots';
			/**
			 * @property `noRescale`
			 */
			'no-rescale'?: boolean;
		};
		events: {};
		cssProperties: {
			'--nf-background-color'?: string;
			'--nf-background-grid-lines-color'?: string;
			'--nf-background-grid-line-width'?: string;
			'--nf-background-grid-line-spacing'?: string;
		};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfCanvasElement extends SignalWatcher(LitElement) (<nf-interactive-canvas>)
	 * ```
	 * ---
	 * @property `flow` — {`Flow<import("./types.js").NodeRegistry>`}
	 */
	'nf-interactive-canvas': {
		elementClass: HTMLElementTagNameMap['nf-interactive-canvas'];
		properties: {
			flow?: HTMLElementTagNameMap['nf-interactive-canvas']['flow'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfFlowElement extends SignalWatcher(LitElement) (<nf-flow>)
	 * ```
	 * ---
	 * @slot `background`
	 * @slot `background-interactive`
	 * @slot `foreground`
	 * @slot `foreground-interactive`
	 * @property `flow` — {`{ attribute: boolean; }`}
	 */
	'nf-flow': {
		elementClass: HTMLElementTagNameMap['nf-flow'];
		properties: {
			flow?: HTMLElementTagNameMap['nf-flow']['flow'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {
			background?: string;
			'background-interactive'?: string;
			foreground?: string;
			'foreground-interactive'?: string;
		};
	};
	/**
	 * ```jsx
	 * class NfHandleElement extends SignalWatcher(LitElement) (<nf-handle>)
	 * ```
	 * ---
	 */
	'nf-handle': {
		elementClass: HTMLElementTagNameMap['nf-handle'];
		properties: {};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfLinksElement extends SignalWatcher(LitElement) (<nf-links>)
	 * ```
	 * ---
	 * @property `slot` — {`"foreground-interactive"`}
	 * @property `flow` — {`GenericFlow`}
	 */
	'nf-links': {
		elementClass: HTMLElementTagNameMap['nf-links'];
		properties: {
			slot?: HTMLElementTagNameMap['nf-links']['slot'];
			flow?: HTMLElementTagNameMap['nf-links']['flow'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfNodeElement extends SignalWatcher(LitElement) (<nf-node>)
	 * ```
	 * ---
	 * @property `node` — {`Node<import("./types.js").NodeDefinition>`}
	 */
	'nf-node': {
		elementClass: HTMLElementTagNameMap['nf-node'];
		properties: {
			node?: HTMLElementTagNameMap['nf-node']['node'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class NfPortElement extends SignalWatcher(LitElement) (<nf-port>)
	 * ```
	 * ---
	 * @attribute `cableoffset` — {`number`}
	 * @property `port` — {`GenericPort`}
	 * @property `cableOffset` — {`number`}
	 */
	'nf-port': {
		elementClass: HTMLElementTagNameMap['nf-port'];
		properties: {
			port?: HTMLElementTagNameMap['nf-port']['port'];
			/**
			 * @attribute `cableoffset`
			 */
			cableOffset?: HTMLElementTagNameMap['nf-port']['cableOffset'];
		};
		attributes: {
			/**
			 * @property `cableOffset`
			 */
			cableoffset?: number;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
}
interface GlobalCss {
	properties: {};
}
declare global {
	interface HTMLElementTagNameMap {
		'nf-background': import('./../background.el.js').NfBackgroundElement;
		'nf-interactive-canvas': import('./../canvas.el.js').NfCanvasElement;
		'nf-flow': import('./../flow.el.js').NfFlowElement;
		'nf-handle': import('./../handle.el.js').NfHandleElement;
		'nf-links': import('./../links.el.js').NfLinksElement;
		'nf-node': import('./../node.el.js').NfNodeElement;
		'nf-port': import('./../port.el.js').NfPortElement;
	}
	interface GlobalEventHandlersEventMap {}
}
import type { CustomElementsExternals } from './../custom-elements.externals';
interface CustomElements extends CustomElementsLocal, CustomElementsExternals {}
export type {
	CustomElements,
	CustomElementsLocal,
	GlobalCss,
	CustomElementsExternals,
};

declare module 'jsx-forge/jsx-runtime' {
	namespace JSX {
		interface IntrinsicElements
			extends JSX.MappedCustomElements<CustomElements, JSX.BaseHTMLElement> {}
	}
}
